# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CD-Hu4AYz77LnpQM8KZuhFc3YO6fIdsC
"""

# %%
# !pip install DeepMIMO==4.0.0b10

# %%
# %%
# =============================================================================
# 1. IMPORTS AND WARNINGS SETUP
#    - Load necessary PyTorch modules, utilities, and suppress UserWarnings
# =============================================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau
import os
import torch
from tqdm import tqdm
import math
# from utils import (generate_channels_and_labels, tokenizer_train, tokenizer, make_sample, nmse_loss,
                #    create_train_dataloader, patch_maker, count_parameters, train_lwm)
import argparse
import numpy as np
# import pretrained_model  # Assuming this contains the LWM model definition
import matplotlib.pyplot as plt
import warnings
import os
import bisect
# from collections import defaultdict
from tqdm import tqdm
warnings.filterwarnings("ignore", category=UserWarning)
# from utils import *
import deepmimo as dm

import numpy as np
import random
from tqdm import tqdm
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.cluster import KMeans
from dataset.dataloaders_play import MySeqDataLoader, ScenarioDataset, create_mixed_dataloader
import wandb
from utils.utils import *
from models_play import PathDecoder, GPTPathDecoder, GPTPathDecoderEnv, PathDecoderEnv
# %%




def evaluate_model(model, val_loader, max_generate=26, log_to_wandb=False):
    model.eval()

    delay_errors = []
    power_errors = []
    phase_errors = []
    path_length_rmses = []



    delay_maes = []
    power_maes = []
    phase_maes = []
    path_length_maes = []
    with torch.no_grad():
        outer_bar = tqdm(val_loader, desc="Evaluating (batches)", leave=True)

        for prompts, paths, path_lengths, interactions, env, env_prop, path_padding_mask in outer_bar:
            prompts = prompts.cuda()
            paths = paths.cuda()
            path_lengths = path_lengths.cuda()
            env = env.cuda()
            env_prop = env_prop.cuda()
            path_padding_mask = path_padding_mask.cuda()

            # Inner tqdm to show per-sample progress
            inner_bar = tqdm(range(prompts.size(0)),
                             desc="   Processing samples",
                             leave=False)

            for b in inner_bar:
                generated, path_lengths_pred, inter_str_pred = generate_paths(model, prompts[b], max_steps=max_generate)

                generated = generated.cuda()
                # Use path length to get valid positions (mask-based; pad value is 0)
                n_valid = int(round(path_lengths[b].item() * 25))
                gt = paths[b][1:1 + n_valid, :3]  # only (delay, power, phase)

                T = min(len(gt), len(generated))
                pred = generated[:T]
                gt = gt[:T]

                # ---- Compute Metrics ----
                delay_rmse = torch.mean((pred[:,0] - gt[:,0])**2).sqrt().item()
                delay_mae = torch.mean(torch.abs(pred[:,0] - gt[:,0])).item()

                power_rmse = torch.mean((pred[:,1]/0.01 - gt[:,1]/0.01)**2).sqrt().item()
                power_mae = torch.mean((torch.abs(pred[:,1]/0.01 - gt[:,1]/0.01))).item()


                # Phase errors
                y_hat_angles = (pred[:,2] / (np.pi/180))
                y_angles = (gt[:,2] / (np.pi/180))
                # phase_rmse =    (torch.mean(y_hat_angles - y_angles)**2).sqrt().item()
                phase_circular_dist = (y_hat_angles - y_angles + 180) % 360 - 180
                phase_rmse = torch.mean(phase_circular_dist**2).sqrt().item()
                phase_mae = torch.mean(torch.abs(phase_circular_dist)).item()

                # Path length RMSE
                # print(path_lengths_pred, path_lengths[b],)
                length_rmse = (torch.mean( (path_lengths_pred - path_lengths[b])**2)).sqrt().item()
                length_mae = (torch.mean(torch.abs(path_lengths_pred - path_lengths[b]))).item()


                # Save metrics
                delay_errors.append(delay_rmse)
                power_errors.append(power_rmse)
                phase_errors.append(phase_rmse)
                path_length_rmses.append(length_rmse)

                delay_maes.append(delay_mae)
                power_maes.append(power_mae)
                phase_maes.append(phase_mae)
                path_length_maes.append(length_mae)
                # Show live metric values in tqdm
                inner_bar.set_postfix({
                    "delay": f"{delay_rmse:.3f}",
                    "power": f"{power_rmse:.3f}",
                    "phase": f"{phase_rmse:.3f}",
                    "length": f"{length_rmse:.3f}",
                    "delay": f"{delay_mae:.3f}",
                    "power": f"{power_mae:.3f}",
                    "phase": f"{phase_mae:.3f}",
                    "length": f"{length_mae:.3f}"
                })

                # wandb logging
                if log_to_wandb:
                    wandb.log({
                        "test_delay_rmse": delay_rmse,
                        "test_power_rmse": power_rmse,
                        "test_phase_circ_err": phase_rmse,
                        "test_stop_length_rmse": length_rmse,
                        "test_delay_mae": delay_mae,
                        "test_power_mae": power_mae,
                        "test_phase_circ_err_mae": phase_mae,
                        "test_stop_length_mae": length_mae,
                    })
            # print("Batch evaluation complete.")

            # print("\n================= Up toBATCH EVALUATION RESULTS =================")
            # print(f"Avg Delay RMSE           : {np.mean(delay_errors):.4f} µs")
            # print(f"Avg Power RMSE           : {np.mean(power_errors):.4f} dB")
            # print(f"Avg Phase RMSE           : {np.mean(phase_errors):.4f} degrees")
            # print(f"Avg Path Length RMSE     : {np.mean(path_length_rmses):.4f}")
            # print(f"Avg Delay MAE           : {np.mean(delay_maes):.4f} µs")
            # print(f"Avg Power MAE           : {np.mean(power_maes):.4f} dB")
            # print(f"Avg Phase MAE           : {np.mean(phase_maes):.4f} degrees")
            # print(f"Avg Path Length MAE     : {np.mean(path_length_maes):.4f}")
            # print("============================================================")


    # ---- Final Aggregated Results ----
    avg_delay = np.mean(delay_errors)
    avg_power = np.mean(power_errors)
    avg_phase = np.mean(phase_errors)
    avg_path_length_rmse = np.mean(path_length_rmses)

    avg_delay_mae = np.mean(delay_maes)
    avg_power_mae = np.mean(power_maes)
    avg_phase_mae = np.mean(phase_maes)
    avg_path_length_mae= np.mean(path_length_maes)

    print("\n=================  Final EVALUATION RESULTS =================")
    print(f"Delay RMSE           : {avg_delay:.4f} µs")
    print(f"Power RMSE           : {avg_power:.4f} dB")
    print(f"Phase RMSE           : {avg_phase:.4f} degrees")
    print(f"Path Length RMSE     : {avg_path_length_rmse:.4f}")

    print(f"Delay MAE           : {avg_delay_mae:.4f} µs")
    print(f"Power MAE           : {avg_power_mae:.4f} dB")
    print(f"Phase MAE           : {avg_phase_mae:.4f} degrees")
    print(f"Path Length MAE     : {avg_path_length_mae:.4f}")
    print("=====================================================\n")

    if log_to_wandb:
        wandb.run.summary["test_delay_rmse"] = avg_delay
        wandb.run.summary["test_power_rmse"] = avg_power
        wandb.run.summary["test_phase_circ_err"] = avg_phase
        wandb.run.summary["test_path_length_rmse"] = avg_path_length_rmse

        wandb.run.summary["test_delay_mae"] = avg_delay_mae
        wandb.run.summary["test_power_mae"] = avg_power_mae
        wandb.run.summary["test_phase_circ_err_mae"] = avg_phase_mae
        wandb.run.summary["test_path_length_mae"] = avg_path_length_mae

    return avg_delay, avg_power, avg_phase, avg_path_length_rmse, avg_delay_mae, avg_power_mae, avg_phase_mae,avg_path_length_mae





# %%


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# -------------------- Cluster center+std conditioning --------------------
def _convert_feature_value(key, value):
    if key == "delay":
        return float(value) * 1e6
    if key == "power":
        return float(value) * 0.01
    if key in ["phase", "aoa_az", "aoa_el"]:
        return float(value) * (np.pi / 180.0)
    return float(value)


def _normalize_feature_value(dataloader_obj, key, value):
    if getattr(dataloader_obj, "normalizers", None) and getattr(dataloader_obj, "apply_normalizers", None):
        if key in dataloader_obj.apply_normalizers:
            stat = dataloader_obj.normalizers.get(key, None)
            if stat is not None:
                return (value - stat["mean"]) / (stat["std"] + 1e-8)
    return value


def _sorted_path_indices(df, idx, sort_by):
    delays_raw = np.array(df["delay"][idx])
    powers_raw = np.array(df["power"][idx])
    if sort_by == "power":
        return np.argsort(-powers_raw)
    return np.argsort(delays_raw)


def _collect_step_vectors_from_base_dataset(base_dataset, feature_keys, max_path_len):
    df = base_dataset.dataset_filtered
    n_samples = len(df["delay"])
    step_vectors = [[] for _ in range(max_path_len)]
    rx_xy_list = []
    seq_vectors = []
    valid_lens = []
    mins = np.array(base_dataset.mins)
    maxs = np.array(base_dataset.maxs)
    norm = getattr(base_dataset, "normalizers", None)
    apply_norm = getattr(base_dataset, "apply_normalizers", None) or []

    for idx in range(n_samples):
        rx_raw = np.array(df["rx_pos"][idx], dtype=np.float32)
        rx_xy = rx_raw[:2]
        if norm and "pos" in apply_norm:
            rx_xy = (rx_xy - norm["rx_pos"]["mean"][:2]) / (norm["rx_pos"]["std"][:2] + 1e-8)
        else:
            rx_xy = (rx_xy - mins[:2]) / (maxs[:2] - mins[:2] + 1e-8)
        rx_xy_list.append(rx_xy)

        seq = np.zeros((max_path_len, len(feature_keys)), dtype=np.float32)
        indices = _sorted_path_indices(df, idx, base_dataset.sort_by)
        step = 0
        for path_idx in indices:
            if step >= max_path_len:
                break
            vec = []
            broken = False
            for k in feature_keys:
                v = np.array(df[k][idx])[path_idx]
                if np.isnan(v):
                    broken = True
                    break
                vv = _convert_feature_value(k, v)
                vv = _normalize_feature_value(base_dataset, k, vv)
                vec.append(vv)
            if broken:
                break
            vec = np.array(vec, dtype=np.float32)
            seq[step] = vec
            step_vectors[step].append(vec)
            step += 1
        seq_vectors.append(seq)
        valid_lens.append(step)

    return (
        np.array(rx_xy_list, dtype=np.float32),
        np.array(seq_vectors, dtype=np.float32),
        np.array(valid_lens, dtype=np.int64),
        step_vectors,
    )


def _scenario_env_signature(env_tensor, decimals=6):
    env_np = np.asarray(env_tensor, dtype=np.float32).reshape(-1)
    return tuple(np.round(env_np, decimals=decimals).tolist())


def compute_feature_kmeans_cluster_stats_for_concat_dataset(concat_dataset, feature_keys, max_path_len=26, n_clusters=4, random_state=42):
    """
    Compute step-wise KMeans centers/std separately for each scenario dataset.
    """
    n_features = len(feature_keys)
    scenario_cluster_stats = {}
    for wrapped in concat_dataset.datasets:
        base = wrapped.base_dataset if hasattr(wrapped, "base_dataset") else wrapped
        _, _, _, step_vectors = _collect_step_vectors_from_base_dataset(base, feature_keys, max_path_len)
        env_signature = _scenario_env_signature(base[0][4].cpu().numpy())
        scenario_name = getattr(wrapped, "scenario_name", f"scenario_{len(scenario_cluster_stats)}")

        centers = np.zeros((max_path_len, n_clusters, n_features), dtype=np.float32)
        stds = np.zeros((max_path_len, n_clusters, n_features), dtype=np.float32)
        for t in range(max_path_len):
            arr = np.array(step_vectors[t], dtype=np.float32)
            if len(arr) == 0:
                continue
            if len(arr) < n_clusters:
                reps = [arr[min(i, len(arr) - 1)] for i in range(n_clusters)]
                c = np.stack(reps, axis=0)
                s = np.stack([np.std(arr, axis=0)] * n_clusters, axis=0)
            else:
                km = KMeans(n_clusters=n_clusters, random_state=random_state, n_init=10)
                labels = km.fit_predict(arr)
                c = km.cluster_centers_.astype(np.float32)
                s = np.zeros_like(c)
                for k in range(n_clusters):
                    pts = arr[labels == k]
                    if len(pts) > 0:
                        s[k] = np.std(pts, axis=0)
            centers[t] = c
            stds[t] = s
        scenario_cluster_stats[scenario_name] = {
            "env_signature": env_signature,
            "centers": centers,
            "stds": stds,
        }
    return scenario_cluster_stats


def precompute_train_cluster_center_std_sequences_for_concat_dataset(concat_dataset, scenario_cluster_stats, feature_keys, max_path_len=26):
    """
    Build NN-retrievable per-sample sequence of nearest cluster center+std for each scenario.
    """
    n_features = len(feature_keys)
    scenario_lookup_data = {}
    for wrapped in concat_dataset.datasets:
        base = wrapped.base_dataset if hasattr(wrapped, "base_dataset") else wrapped
        scenario_name = getattr(wrapped, "scenario_name", None)
        if scenario_name not in scenario_cluster_stats:
            continue
        cluster_centers = scenario_cluster_stats[scenario_name]["centers"]
        cluster_stds = scenario_cluster_stats[scenario_name]["stds"]
        rx_xy, seq_vectors, valid_lens, _ = _collect_step_vectors_from_base_dataset(base, feature_keys, max_path_len)
        N = seq_vectors.shape[0]
        out = np.zeros((N, max_path_len, 2 * n_features), dtype=np.float32)
        for i in range(N):
            valid = int(valid_lens[i])
            for t in range(valid):
                vec = seq_vectors[i, t]
                cc = cluster_centers[t]  # (K, F)
                dist = np.linalg.norm(cc - vec[None, :], axis=1)
                nn = int(np.argmin(dist))
                out[i, t, :n_features] = cluster_centers[t, nn]
                out[i, t, n_features:] = cluster_stds[t, nn]
        scenario_lookup_data[scenario_name] = {
            "env_signature": scenario_cluster_stats[scenario_name]["env_signature"],
            "train_rx_pos": rx_xy,
            "train_cluster_center_std": out,
            "train_valid_len": valid_lens,
        }

    return scenario_lookup_data


def lookup_cluster_center_std_by_position(prompts, env, scenario_lookup_data, device, prompt_rx_slice=(3, 5)):
    B = prompts.shape[0]
    rx_query = prompts[:, prompt_rx_slice[0]:prompt_rx_slice[1]].detach().cpu().numpy()
    if not scenario_lookup_data:
        return None, None
    first_lookup = next(iter(scenario_lookup_data.values()))
    max_T = first_lookup["train_cluster_center_std"].shape[1]
    D = first_lookup["train_cluster_center_std"].shape[2]
    batch = np.zeros((B, max_T, D), dtype=np.float32)
    pad_mask = np.ones((B, max_T), dtype=bool)
    scenario_lookup_by_env = {
        lookup["env_signature"]: lookup for lookup in scenario_lookup_data.values()
    }
    for b in range(B):
        env_signature = _scenario_env_signature(env[b].detach().cpu().numpy())
        scenario_lookup = scenario_lookup_by_env.get(env_signature)
        if scenario_lookup is None:
            continue
        train_rx_pos = scenario_lookup["train_rx_pos"]
        train_cluster_center_std = scenario_lookup["train_cluster_center_std"]
        train_valid_len = scenario_lookup["train_valid_len"]
        if train_rx_pos.shape[0] == 0:
            continue
        pos_b = rx_query[b]
        dist = np.sqrt(np.sum((train_rx_pos - pos_b) ** 2, axis=1))
        nn_idx = int(np.argmin(dist))
        batch[b] = train_cluster_center_std[nn_idx]
        valid = int(train_valid_len[nn_idx])
        pad_mask[b, :valid] = False
        pad_mask[b, valid:] = True
    return (
        torch.tensor(batch, dtype=torch.float32, device=device),
        torch.tensor(pad_mask, dtype=torch.bool, device=device),
    )


class PathDecoderEnvClusterEncoderAdapter(nn.Module):
    """
    Learns cluster center+std embeddings and injects them into prompt conditioning.
    """
    def __init__(self, backbone, hidden_dim, cluster_feature_dim, prompt_dim=6):
        super().__init__()
        self.backbone = backbone
        self.cluster_embed = nn.Sequential(
            nn.Linear(cluster_feature_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
        )
        self.cluster_to_prompt = nn.Linear(hidden_dim, prompt_dim)

    def forward(self, prompts, paths, interactions, environment_properties, environment, pre_train, cluster_center_std=None, cluster_pad_mask=None):
        B = prompts.shape[0]
        if cluster_center_std is None:
            cluster_summary = torch.zeros(B, self.cluster_to_prompt.in_features, device=prompts.device, dtype=prompts.dtype)
        else:
            emb = self.cluster_embed(cluster_center_std)
            if cluster_pad_mask is not None:
                valid = (~cluster_pad_mask).float().unsqueeze(-1)
                denom = valid.sum(dim=1).clamp_min(1.0)
                cluster_summary = (emb * valid).sum(dim=1) / denom
            else:
                cluster_summary = emb.mean(dim=1)
        prompts_aug = prompts + self.cluster_to_prompt(cluster_summary)
        return self.backbone(prompts_aug, paths, interactions, environment_properties, environment, pre_train)


class PathDecoderClusterEncoderAttentionFix1(nn.Module):
    """
    Cluster-aware pretraining decoder that keeps cluster conditioning in memory
    while zeroing TX/RX prompt positions during pretraining.
    """
    def __init__(
        self,
        prompt_dim=6,
        hidden_dim=512,
        n_layers=8,
        n_heads=8,
        cluster_feature_dim=None,
        max_T=35,
        prefix_len=4,
        cluster_encoder_layers=2,
        zero_prompt_positions_for_pretrain=True,
    ):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.prompt_dim = prompt_dim
        self.prefix_len = prefix_len
        self.max_T = max_T
        self.zero_prompt_positions_for_pretrain = zero_prompt_positions_for_pretrain

        self.cluster_embed = nn.Sequential(
            nn.Linear(cluster_feature_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
        )
        self.prompt_to_prefix = nn.Linear(prompt_dim, prefix_len * hidden_dim)
        self.path_in = nn.Linear(12, hidden_dim)
        self.pos_emb = nn.Embedding(max_T + 64, hidden_dim)
        self.cluster_pos_emb = nn.Embedding(max_T, hidden_dim)
        self.memory_pos_emb = nn.Embedding(prefix_len + max_T, hidden_dim)
        self.environment_embed = nn.Linear(4, hidden_dim)
        self.environment_prop_embed = nn.Linear(6, hidden_dim)
        self.interaction_head = nn.Linear(hidden_dim, 4)

        cluster_encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=n_heads,
            dim_feedforward=4 * hidden_dim,
            batch_first=True,
        )
        self.cluster_encoder = nn.TransformerEncoder(cluster_encoder_layer, num_layers=cluster_encoder_layers)
        self.cluster_norm = nn.LayerNorm(hidden_dim)

        decoder_layer = nn.TransformerDecoderLayer(
            d_model=hidden_dim,
            nhead=n_heads,
            dim_feedforward=4 * hidden_dim,
            batch_first=True,
        )
        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=n_layers)

        self.out_delay = nn.Sequential(nn.Linear(hidden_dim, 1), nn.Sigmoid())
        self.out_power = nn.Sequential(nn.Linear(hidden_dim, 1))
        self.out = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 6),
            nn.Tanh(),
        )
        self.pathcount_head = nn.Sequential(
            nn.Linear(prefix_len * hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
        )

    def _prepare_prompts(self, prompts, pre_train=False):
        if pre_train and self.zero_prompt_positions_for_pretrain:
            prompts = prompts.clone()
            prompts[:, :self.prompt_dim] = 0.0
        return prompts

    def _build_memory(self, prompts, cluster_center_std=None, cluster_pad_mask=None, pre_train=False):
        batch_size = prompts.size(0)
        device = prompts.device

        prompts = self._prepare_prompts(prompts, pre_train=pre_train)
        prefix = self.prompt_to_prefix(prompts).view(batch_size, self.prefix_len, self.hidden_dim)
        prefix_mask = torch.zeros(batch_size, self.prefix_len, dtype=torch.bool, device=device)

        if cluster_center_std is None:
            cluster_tokens = prefix.new_zeros(batch_size, 0, self.hidden_dim)
            cluster_pad_mask = torch.zeros(batch_size, 0, dtype=torch.bool, device=device)
        else:
            cluster_tokens = self.cluster_embed(cluster_center_std)
            if cluster_pad_mask is None:
                cluster_pad_mask = torch.zeros(
                    batch_size,
                    cluster_tokens.size(1),
                    dtype=torch.bool,
                    device=device,
                )
            else:
                cluster_pad_mask = cluster_pad_mask.to(device=device, dtype=torch.bool)

            cluster_pos = self.cluster_pos_emb(torch.arange(cluster_tokens.size(1), device=device)).unsqueeze(0)
            cluster_tokens = cluster_tokens + cluster_pos
            safe_cluster_pad_mask = cluster_pad_mask.clone()
            if safe_cluster_pad_mask.size(1) > 0:
                all_padded = safe_cluster_pad_mask.all(dim=1)
                safe_cluster_pad_mask[all_padded, 0] = False
                cluster_tokens[all_padded] = 0.0
            cluster_tokens = self.cluster_encoder(
                cluster_tokens,
                src_key_padding_mask=safe_cluster_pad_mask,
            )
            cluster_tokens = self.cluster_norm(cluster_tokens)

        memory = torch.cat([prefix, cluster_tokens], dim=1)
        memory_pos = self.memory_pos_emb(torch.arange(memory.size(1), device=device)).unsqueeze(0)
        memory = memory + memory_pos
        memory_mask = torch.cat([prefix_mask, cluster_pad_mask], dim=1)
        return prefix, memory, memory_mask

    def forward(self, prompts, paths, interactions, environment_properties, environment, pre_train, cluster_center_std=None, cluster_pad_mask=None):
        batch_size, path_len, _ = paths.shape
        prefix, memory, memory_mask = self._build_memory(
            prompts,
            cluster_center_std=cluster_center_std,
            cluster_pad_mask=cluster_pad_mask,
            pre_train=pre_train,
        )

        env_embedding = self.environment_embed(environment).unsqueeze(1)
        env_prop_embedding = self.environment_prop_embed(environment_properties)

        phase = paths[:, :, 2]
        sinp = torch.sin(phase)
        cosp = torch.cos(phase)
        aoa_az = paths[:, :, 3]
        sin_az = torch.sin(aoa_az)
        cos_az = torch.cos(aoa_az)
        aoa_el = paths[:, :, 4]
        sin_el = torch.sin(aoa_el)
        cos_el = torch.cos(aoa_el)

        x = torch.stack(
            [paths[:, :, 0], paths[:, :, 1], sinp, cosp, sin_az, cos_az, sin_el, cos_el],
            dim=-1,
        )
        interactions_clean = interactions.clone()
        interactions_clean[interactions_clean == -1] = 0
        x = torch.cat([x, interactions_clean], dim=-1)
        x = self.path_in(x)
        x = torch.cat([env_embedding, env_prop_embedding, x], dim=1)

        total_len = x.size(1)
        pos = self.pos_emb(torch.arange(total_len, device=x.device)).unsqueeze(0)
        x = x + pos
        causal_mask = torch.triu(torch.ones(total_len, total_len, device=x.device), diagonal=1).bool()

        h = self.decoder(
            tgt=x,
            memory=memory,
            tgt_mask=causal_mask,
            memory_key_padding_mask=memory_mask,
        )
        h_paths = h[:, -(path_len):, :]

        out = self.out(h_paths)
        delay_pred = self.out_delay(h_paths).squeeze(-1)
        power_pred = self.out_power(h_paths).squeeze(-1)
        phase_sin_pred = out[:, :, 0]
        phase_cos_pred = out[:, :, 1]
        az_sin_pred = out[:, :, 2]
        az_cos_pred = out[:, :, 3]
        el_sin_pred = out[:, :, 4]
        el_cos_pred = out[:, :, 5]

        phase_pred = torch.atan2(phase_sin_pred, phase_cos_pred)
        az_pred = torch.atan2(az_sin_pred, az_cos_pred)
        el_pred = torch.atan2(el_sin_pred, el_cos_pred)
        interaction_logits = self.interaction_head(h_paths)

        prefix_flat = prefix.reshape(batch_size, -1)
        pathcounts = self.pathcount_head(prefix_flat)

        return (
            delay_pred,
            power_pred,
            phase_sin_pred,
            phase_cos_pred,
            phase_pred,
            az_sin_pred,
            az_cos_pred,
            az_pred,
            el_sin_pred,
            el_cos_pred,
            el_pred,
            pathcounts,
            interaction_logits,
        )



def train_with_interactions(model, config, task = None):
    """
    Modified training loop with interaction prediction.
    """
    all_scenarios = os.listdir('deepmimo_scenarios')


    all_scenarios = ['city_47_chicago_3p5', 'city_23_beijing_3p5', 'city_91_xiangyang_3p5', 'city_17_seattle_3p5_s', 'city_12_fortworth_3p5', 'city_92_sãopaulo_3p5', 'city_35_san_francisco_3p5', 'city_10_florida_villa_7gp_1758095156175', 'city_19_oklahoma_3p5_s', 'city_74_chiyoda_3p5']
    all_scenarios  = ['city_0_newyork_3p5'] + all_scenarios
    random.shuffle(all_scenarios)

    pre_train = config.get("pre_train", True)
    best_val_loss = float('inf')
    checkpoint_path = f"{config['experiment']}_clusters_{config['n_clusters']}_best_model_checkpoint.pth"
    os.makedirs("checkpoints20M", exist_ok=True)
    checkpoint_path = os.path.join("checkpoints20M", checkpoint_path)



    # %%




    optimizer = torch.optim.AdamW(model.parameters(), lr=config["LR"])
    # scheduler = ReduceLROnPlateau(optimizer, factor=0.5, patience=2, mode="min")
    scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
        optimizer,
        T_0=25,      # Restart every 10 epochs
        T_mult=1,    # Double the period after each restart
        eta_min=1e-8 # Minimum LR
    )


    # Create mixed dataloaders once at the beginning
    print("Creating mixed training dataloader...")
    train_loader = create_mixed_dataloader(all_scenarios[:], config, train=True)
    
    print("Creating mixed validation dataloader...")
    val_loader = create_mixed_dataloader(all_scenarios[:], config, train=False)
    cluster_lookup_data = None
    if config.get("use_cluster_conditioning", True):
        cluster_features = config.get("cluster_features", ["delay", "power", "aoa_az", "aoa_el", "phase"])
        n_clusters = config.get("n_clusters", 5)
        max_path_len_clusters = config.get("max_path_len_clusters", 25)
        scenario_cluster_stats = compute_feature_kmeans_cluster_stats_for_concat_dataset(
            train_loader.dataset,
            feature_keys=cluster_features,
            max_path_len=max_path_len_clusters,
            n_clusters=n_clusters,
        )
        cluster_lookup_data = precompute_train_cluster_center_std_sequences_for_concat_dataset(
            train_loader.dataset,
            scenario_cluster_stats=scenario_cluster_stats,
            feature_keys=cluster_features,
            max_path_len=max_path_len_clusters,
        )
        print(f"Prepared scenario-local cluster center+std lookup for features={cluster_features}")
    best_val_loss = float('inf')
    


    for epoch in range(config["epochs"]):
        random.shuffle(all_scenarios)
        train_losses = []
        train_loss_delay = []
        train_loss_power = []
        train_loss_phase = []
        train_loss_path_length = []
        train_loss_interaction = []  # NEW
        train_path_length_rmse = []
        train_loss_az = []
        train_loss_el = []
        train_ch_nmse = []

        val_losses = []
        val_loss_delay = []
        val_loss_power = []
        val_loss_phase = []
        val_loss_path_length = []
        val_loss_interaction = []  # NEW
        val_path_length_rmse = []
        val_loss_az = []
        val_loss_el = []
        # if epoch > 100:
        #     config['BATCH_SIZE'] = 64
        #     del train_loader, val_loader
        #     print("Creating mixed training dataloader...")
        #     train_loader = create_mixed_dataloader(all_scenarios[:], config, train=True)
            
        #     print("Creating mixed validation dataloader...")
        #     val_loader = create_mixed_dataloader(all_scenarios[:], config, train=False)
        # -------------------- TRAINING --------------------
        model.train()

        pbar = tqdm(train_loader, desc=f"Epoch {epoch} [Train]", leave=False)
        for prompts, paths, path_lengths, interactions, env, env_prop, path_padding_mask in pbar:  # NEW: added interactions
            prompts = prompts.cuda()
            paths = paths.cuda()
            path_lengths = path_lengths.cuda()
            interactions = interactions.cuda()  # NEW
            env = env.cuda()
            env_prop = env_prop.cuda()
            path_padding_mask = path_padding_mask.cuda()
            cluster_center_std, cluster_pad_mask = None, None
            if cluster_lookup_data is not None:
                cluster_center_std, cluster_pad_mask = lookup_cluster_center_std_by_position(
                    prompts, env, cluster_lookup_data, prompts.device
                )

            paths_in = paths[:, :-1, :]
            # Optional target noise (use mask to perturb only valid positions)
            p_noise = config.get("TARGET_NOISE_PROB", 0.0)
            if p_noise > 0:
                noise_params = config.get("TARGET_NOISE_PARAMS")
                paths_in = add_noise_to_paths(paths_in, path_padding_mask[:, :-1], p_noise=p_noise, noise_params=noise_params)
            interactions_in = interactions[:, :-1, :]

            paths_out = paths[:, 1:, :]
            interactions_out = interactions[:, 1:, :]  # NEW: shift targets     


            (delay_pred, power_pred, phase_sin_pred, phase_cos_pred, phase_pred,
            az_sin_pred, az_cos_pred, az_pred, el_sin_pred, el_cos_pred, el_pred,
            path_length_pred, interaction_logits) = model(
                prompts, paths_in, interactions_in, env_prop, env, pre_train,
                cluster_center_std=cluster_center_std, cluster_pad_mask=cluster_pad_mask
            )

            (total_loss, loss_delay, loss_power, loss_phase,
            loss_az, loss_el, loss_path_length, loss_interaction,loss_channel) = masked_loss(
                delay_pred, power_pred, phase_sin_pred, phase_cos_pred,phase_pred,
                az_sin_pred, az_cos_pred, az_pred, el_sin_pred, el_cos_pred,el_pred,
                path_length_pred, interaction_logits, paths_out, path_lengths,
                interactions_out, finetune=task, pad_value=config["PAD_VALUE"],
                interaction_weight=config.get("interaction_weight", 0.1),
                path_padding_mask=path_padding_mask
            )
            
            optimizer.zero_grad()
            total_loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()
            
            path_length_rmse = compute_stop_metrics(path_length_pred.detach().squeeze(-1),
                                                    path_lengths)

            train_ch_nmse.append(loss_channel)
            train_losses.append(total_loss.item())
            train_loss_delay.append(loss_delay.item())
            train_loss_power.append(loss_power.item())
            train_loss_phase.append(loss_phase.item())
            train_loss_path_length.append(loss_path_length.item())
            # track aoa losses
            # if 'train_loss_az' not in locals():
            #     train_loss_az = []
            #     train_loss_el = []
            train_loss_az.append(loss_az.item())
            train_loss_el.append(loss_el.item())
            train_loss_interaction.append(loss_interaction.item())  # NEW
            train_path_length_rmse.append(path_length_rmse)
            current_lr = optimizer.param_groups[0]["lr"]
            pbar.set_postfix({
                "loss": f"{total_loss.item():.4f}",
                "delay": f"{loss_delay.item():.4f}",
                
                "power": f"{loss_power.item():.4f}",
                "phase": f"{loss_phase.item():.4f}",
                "az": f"{loss_az.item():.4f}",
                "el": f"{loss_el.item():.4f}",
                "inter": f"{loss_interaction.item():.4f}",  # NEW
                "path_rmse": f"{path_length_rmse:.4f}",
                "ch_nmse":f"{loss_channel:.4f}",
                "lr": f"{current_lr:.2e}"
            })

        avg_train_loss = np.mean(train_losses)
        avg_train_delay = np.mean(train_loss_delay)
        avg_train_power = np.mean(train_loss_power)
        avg_train_phase = np.mean(train_loss_phase)
        avg_train_az = np.mean(train_loss_az) 
        avg_train_el = np.mean(train_loss_el)
        avg_train_path_length = np.mean(train_loss_path_length)
        avg_train_interaction = np.mean(train_loss_interaction)  # NEW
        avg_train_path_length_rmse = np.mean(train_path_length_rmse)

        # -------------------- VALIDATION --------------------
        model.eval()

        with torch.no_grad():
            pbar = tqdm(val_loader, desc=f"Epoch {epoch} [Val]", leave=False)
            for prompts, paths, path_lengths, interactions, env, env_prop, path_padding_mask in pbar:  # NEW
                prompts = prompts.cuda()
                paths = paths.cuda()
                path_lengths = path_lengths.cuda()
                interactions = interactions.cuda()  # NEW
                env = env.cuda()
                env_prop = env_prop.cuda()
                path_padding_mask = path_padding_mask.cuda()
                cluster_center_std, cluster_pad_mask = None, None
                if cluster_lookup_data is not None:
                    cluster_center_std, cluster_pad_mask = lookup_cluster_center_std_by_position(
                        prompts, env, cluster_lookup_data, prompts.device
                    )

                paths_in = paths[:, :-1, :]
                interactions_in = interactions[:, :-1, :]

                paths_out = paths[:, 1:, :]
                interactions_out = interactions[:, 1:, :]  # NEW: shift targets
                
                (delay_pred, power_pred, phase_sin_pred, phase_cos_pred, phase_pred,
                az_sin_pred, az_cos_pred, az_pred, el_sin_pred, el_cos_pred, el_pred,
                path_length_pred, interaction_logits) = model(
                    prompts, paths_in, interactions_in, env_prop, env, pre_train,
                    cluster_center_std=cluster_center_std, cluster_pad_mask=cluster_pad_mask
                )

                (total_loss, loss_delay, loss_power, loss_phase,
                loss_az, loss_el, loss_path_length, loss_interaction,loss_channel) = masked_loss(
                    delay_pred, power_pred, phase_sin_pred, phase_cos_pred,phase_pred,
                    az_sin_pred, az_cos_pred, az_pred, el_sin_pred, el_cos_pred,el_pred,
                    path_length_pred, interaction_logits, paths_out, path_lengths,
                    interactions_out, finetune=task, pad_value=config["PAD_VALUE"],
                    interaction_weight=config.get("interaction_weight", 0.1),
                    path_padding_mask=path_padding_mask
                )

                path_length_rmse = compute_stop_metrics(path_length_pred.detach().squeeze(-1),
                                                    path_lengths)


                val_losses.append(total_loss.item())
                val_loss_delay.append(loss_delay.item())
                val_loss_power.append(loss_power.item())
                val_loss_phase.append(loss_phase.item())
                val_loss_az.append(loss_az.item())
                val_loss_el.append(loss_el.item())
                val_loss_path_length.append(loss_path_length.item())
                val_loss_interaction.append(loss_interaction.item())  # NEW
                val_path_length_rmse.append(path_length_rmse)

                pbar.set_postfix({
                    "val_loss": f"{total_loss.item():.4f}",
                    "inter": f"{loss_interaction.item():.4f}",  # NEW

                })
                break

        avg_val_loss = np.mean(val_losses)
        avg_val_delay = np.mean(val_loss_delay)
        avg_val_power = np.mean(val_loss_power)
        avg_val_phase = np.mean(val_loss_phase)
        avg_val_az = np.mean(val_loss_az) 
        avg_val_el = np.mean(val_loss_el)
        avg_val_path_length = np.mean(val_loss_path_length)
        avg_val_interaction = np.mean(val_loss_interaction)  # NEW
        avg_val_path_length_rmse = np.mean(val_path_length_rmse)
        # scheduler.step(avg_val_loss)
        current_lr = optimizer.param_groups[0]["lr"]

                # -------------------- CHECKPOINT SAVING --------------------
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'scheduler_state_dict': scheduler.state_dict(),
                'best_val_loss': torch.tensor(best_val_loss),
            }, checkpoint_path)
            print(f"  ✓ Best checkpoint saved (val_loss: {best_val_loss:.4f})")

        if config.get("USE_WANDB", False):
            import wandb
            wandb.log({
                "train_loss": avg_train_loss,
                "train_loss_delay": avg_train_delay,
                "train_loss_power": avg_train_power,
                "train_loss_phase": avg_train_phase,
                "train_loss_az": avg_train_az,
                "train_loss_el": avg_train_el,
                "train_loss_path_length": avg_train_path_length,
                "train_loss_interaction": avg_train_interaction,  # NEW
                "train_path_length_rmse": avg_train_path_length_rmse,

                "val_loss": avg_val_loss,
                "val_loss_delay": avg_val_delay,
                "val_loss_power": avg_val_power,
                "val_loss_phase": avg_val_phase,
                "val_loss_az": avg_val_az,
                "val_loss_el": avg_val_el,
                "val_loss_path_length": avg_val_path_length,
                "val_loss_interaction": avg_val_interaction,  # NEW
                "val_path_length_rmse": avg_val_path_length_rmse,
                "epoch": epoch,
                "lr": current_lr,
            })


        print(f"\nEpoch {epoch:02d}")
        print(f"  Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")
        print(f"    Delay: {avg_train_delay:.4f} (val: {avg_val_delay:.4f})")
        print(f"    Power: {avg_train_power:.4f} (val: {avg_val_power:.4f})")
        print(f"    Phase: {avg_train_phase:.4f} (val: {avg_val_phase:.4f})")
        print(f"    Az: {avg_train_az:.4f} (val: {avg_val_az:.4f})")
        print(f"    El: {avg_train_el:.4f} (val: {avg_val_el:.4f})")

        print(f"    Interaction: {avg_train_interaction:.4f} (val: {avg_val_interaction:.4f})")  # NEW
        print(f"    PathLength: {avg_train_path_length:.4f} (val: {avg_val_path_length:.4f})")  # NEW

        print(f"  LR: {current_lr:.3e}")
        scheduler.step()
            # except Exception as e:
            #     print(f"Error during training on scenario {scenario}: {e}")
            #     continue


def train_with_mixed_scenarios(model, config):
    """
    Modified training loop with mixed scenario batches
    """


    # Create mixed dataloaders once at the beginning
    print("Creating mixed training dataloader...")
    train_loader = create_mixed_dataloader(all_scenarios, config, train=True)

    print("Creating mixed validation dataloader...")
    val_loader = create_mixed_dataloader(all_scenarios, config, train=False)

    best_val_loss = float('inf')
    checkpoint_path = f"{config['experiment']}_best_model_checkpoint.pth"

    for epoch in range(config["epochs"]):
        # -------------------- TRAINING --------------------
        model.train()
        train_losses = []
        train_loss_delay = []
        train_loss_power = []
        train_loss_phase = []
        train_loss_path_length = []
        train_loss_interaction = []
        train_path_length_rmse = []
        
        pbar = tqdm(train_loader, desc=f"Epoch {epoch} [Train - Mixed]")
        for prompts, paths, path_lengths, interactions in pbar:
            prompts = prompts.cuda()
            paths = paths.cuda()
            path_lengths = path_lengths.cuda()
            interactions = interactions.cuda()
            
            paths_in = paths[:, :-1, :]
            interactions_in = interactions[:, :-1, :]
            paths_out = paths[:, 1:, :]
            interactions_out = interactions[:, 1:, :]
            
            # Forward pass
            (delay_pred, power_pred, sin_pred, cos_pred, phase_pred,
                path_length_pred, interaction_logits) = model(
                prompts, paths_in, interactions_in
            )
            
            # Compute loss
            (total_loss, loss_delay, loss_power, loss_phase,
                loss_path_length, loss_interaction) = masked_loss_pre_train(
                delay_pred, power_pred, sin_pred, cos_pred, phase_pred,
                path_length_pred, interaction_logits, paths_out, path_lengths,
                interactions_out, pad_value=config['PAD_VALUE'],
                interaction_weight=config.get("interaction_weight", 0.1)
            )
            
            # Backward pass
            optimizer.zero_grad()
            total_loss.backward()
            optimizer.step()
            
            # Track metrics
            path_length_rmse = compute_stop_metrics(
                path_length_pred.detach().squeeze(-1), path_lengths
            )
            
            train_losses.append(total_loss.item())
            train_loss_delay.append(loss_delay.item())
            train_loss_power.append(loss_power.item())
            train_loss_phase.append(loss_phase.item())
            train_loss_path_length.append(loss_path_length.item())
            train_loss_interaction.append(loss_interaction.item())
            train_path_length_rmse.append(path_length_rmse)
            
            pbar.set_postfix({
                "loss": f"{total_loss.item():.4f}",
                "delay": f"{loss_delay.item():.4f}",
                "power": f"{loss_power.item():.4f}",
                "phase": f"{loss_phase.item():.4f}",
                "inter": f"{loss_interaction.item():.4f}",
                "path_rmse": f"{path_length_rmse:.4f}"
            })
        
        # -------------------- VALIDATION --------------------
        model.eval()
        val_losses = []
        val_loss_delay = []
        val_loss_power = []
        val_loss_phase = []
        val_loss_path_length = []
        val_loss_interaction = []
        val_path_length_rmse = []
        
        with torch.no_grad():
            pbar = tqdm(val_loader, desc=f"Epoch {epoch} [Val - Mixed]")
            for prompts, paths, path_lengths, interactions in pbar:
                prompts = prompts.cuda()
                paths = paths.cuda()
                path_lengths = path_lengths.cuda()
                interactions = interactions.cuda()
                
                paths_in = paths[:, :-1, :]
                interactions_in = interactions[:, :-1, :]
                paths_out = paths[:, 1:, :]
                interactions_out = interactions[:, 1:, :]
                
                # Forward pass
                (delay_pred, power_pred, sin_pred, cos_pred, phase_pred,
                    path_length_pred, interaction_logits) = model(
                    prompts, paths_in, interactions_in
                )
                
                # Compute loss
                (total_loss, loss_delay, loss_power, loss_phase,
                    loss_path_length, loss_interaction) = masked_loss_pre_train(
                    delay_pred, power_pred, sin_pred, cos_pred, phase_pred,
                    path_length_pred, interaction_logits, paths_out, path_lengths,
                    interactions_out, pad_value=config['PAD_VALUE'],
                    interaction_weight=config.get("interaction_weight", 0.1)
                )
                
                path_length_rmse = compute_stop_metrics(
                    path_length_pred.detach().squeeze(-1), path_lengths
                )
                
                val_losses.append(total_loss.item())
                val_loss_delay.append(loss_delay.item())
                val_loss_power.append(loss_power.item())
                val_loss_phase.append(loss_phase.item())
                val_loss_path_length.append(loss_path_length.item())
                val_loss_interaction.append(loss_interaction.item())
                val_path_length_rmse.append(path_length_rmse)
        
        # Compute averages
        avg_train_loss = np.mean(train_losses)
        avg_val_loss = np.mean(val_losses)
        
        # Learning rate scheduling
        scheduler.step()
        current_lr = optimizer.param_groups[0]["lr"]
        
        # Checkpoint saving
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'best_val_loss': torch.tensor(best_val_loss),
            }, checkpoint_path)
            print(f"✓ Best checkpoint saved (val_loss: {best_val_loss:.4f})")
        
        # Logging
        if config.get("USE_WANDB", False):
            wandb.log({
                "train_loss": avg_train_loss,
                "train_loss_delay": np.mean(train_loss_delay),
                "train_loss_power": np.mean(train_loss_power),
                "train_loss_phase": np.mean(train_loss_phase),
                "train_loss_path_length": np.mean(train_loss_path_length),
                "train_loss_interaction": np.mean(train_loss_interaction),
                "val_loss": avg_val_loss,
                "val_loss_delay": np.mean(val_loss_delay),
                "val_loss_power": np.mean(val_loss_power),
                "val_loss_phase": np.mean(val_loss_phase),
                "val_loss_path_length": np.mean(val_loss_path_length),
                "val_loss_interaction": np.mean(val_loss_interaction),
                "epoch": epoch,
                "lr": current_lr,
            })
        
        print(f"\nEpoch {epoch:02d}")
        print(f"  Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")
        print(f"  LR: {current_lr:.3e}")


# evaluate_generation(train_loader)
#

# %%
def load_best_checkpoint(model, checkpoint_path="checkpoints2/best_model_checkpoint.pth"):
    """
    Load the best model checkpoint saved during training.

    Args:
        model: The model instance to load the checkpoint into
        checkpoint_path: Path to the checkpoint file

    Returns:
        epoch: Epoch at which best checkpoint was saved
        best_val_loss: Best validation loss achieved
    """
    if not os.path.exists(checkpoint_path):
        print(f"Warning: Checkpoint not found at {checkpoint_path}")
        return None, None

    checkpoint = torch.load(checkpoint_path)
    model.load_state_dict(checkpoint['model_state_dict'])
    epoch = checkpoint['epoch']
    best_avg_val_loss = checkpoint['best_val_loss']

    print(f"✓ Loaded best checkpoint from epoch {epoch} (val_loss: {best_avg_val_loss:.4f})")
    return epoch, best_avg_val_loss

def run_pre_training(n_clusters=5):



    config = {
        "BATCH_SIZE":256,
        "PAD_VALUE": 0,
        "USE_WANDB": True,
        "LR":2e-5,
        "epochs" : 50,
        "interaction_weight": 0.01,  # Weight for interaction loss
        # "experiment": "interacaction_power_only_dec_only",

        # "experiment": f"pre_train_all_scenarios_interaction_weight_0.01_better_scheduler",
        "experiment": f"cluster_noisy_pretrain",
        # "hidden_dim": 512,
        # "n_layers": 6,
        # "n_heads": 4,
        "hidden_dim": 512,
        "n_layers": 8,
        "n_heads": 8,
        "pre_train": True,
        "use_cluster_conditioning": True,
        "n_clusters": n_clusters,
        "max_path_len_clusters": 25,
        "cluster_features": ["delay", "power"],
        # Target noise for generalization: probability and per-parameter (mean, std)
        "TARGET_NOISE_PROB": 0.2,
        "TARGET_NOISE_PARAMS": None,  # None = use add_noise_to_paths defaults; or e.g. {"delay": {"mean": 0, "std": 0.05}, "power": {"mean": 0, "std": 0.002}, "phase": {"mean": 0, "std": 0.1}, "aoa_az": {"mean": 0, "std": 0.08}, "aoa_el": {"mean": 0, "std": 0.04}}}
    }
    model = PathDecoderClusterEncoderAttentionFix1(
        hidden_dim=config["hidden_dim"],
        n_layers=config["n_layers"],
        n_heads=config["n_heads"],
        cluster_feature_dim=2 * len(config.get("cluster_features", ["delay", "power", "aoa_az", "aoa_el", "phase"])),
        prompt_dim=6,
    ).to(device)
    print("Total trainable parameters:", count_parameters(model))
    print(f"N_clusters: {config['n_clusters']}")
    # %%
    if config["USE_WANDB"]:
        import wandb

        wandb.init(
            project="deepmimo-path-decoder",
            config = config
        
        )

    train_with_interactions(model, config)


# Usage:
# 
# # %%
# print(evaluate_model(model, val_loader))




def parse_args():
    parser = argparse.ArgumentParser(description="Train/evaluate the multiscenario direct training model.")
    parser.add_argument("--n_clusters", type =int,  default=5)
    return parser.parse_args()

def main():
    args = parse_args()
    run_pre_training(args.n_clusters)
# %%
# show_example(model, val_loader, sample_index=24)

if __name__ == "__main__":
    main()

##################################################################################################



# Usage:
# train_with_mixed_scenarios(model, config)
